services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend:/app

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./resume.html:/usr/share/nginx/html/index.html:ro
      - ./cv.pdf:/usr/share/nginx/html/cv.pdf:ro
