services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./resume.html:/usr/share/nginx/html/index.html:ro
      - ./cv.pdf:/usr/share/nginx/html/cv.pdf:ro
