name: Build and Push Website

on:
  push:
    branches: [main]
    paths:
      - "resume.html"
      - "cv.pdf"
      - "Dockerfile"
      - "frontend/**"
      - "backend/**"
      - "nginx/**"
      - "flake.nix"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jvandelocht/website

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
